# Generated by Django 2.0.8 on 2018-10-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cadeirafundadorestitulares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatuto',
            name='conteudo',
            field=models.TextField(max_length=1000),
        ),
    ]
