# Generated by Django 2.0.8 on 2018-10-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181015_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoria',
            name='descricao',
            field=models.TextField(),
        ),
    ]
