# Generated by Django 2.0.8 on 2019-10-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cadeirafundadorestitulares_imagem_membro_fundador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeirafundadorestitulares',
            name='imagem_membro_fundador',
        ),
    ]
