# Generated by Django 2.0.8 on 2019-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_cadeirafundadorestitulares_imagem_membro_fundador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeirafundadorestitulares',
            name='imagem_membro_fundador',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
