# Generated by Django 2.0.8 on 2020-05-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cadeirafundadorestitulares_imagem_membro_fundador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeirafundadorestitulares',
            name='numero_da_cadeira',
            field=models.IntegerField(null=True),
        ),
    ]
